### PR TITLE
Solution of 26-10 added

### PR DESCRIPTION
**Pull request by MrDracs**

### CODE REVIEW

**Comment by MrDracs** [comment]
Added the solution of 26th october

**Comment by Gyanthakur** [comment]
> Author

firstly follow the account and mark star on the repo

**Comment by MrDracs** [comment]
done

**Comment by MrDracs** [comment]
> > Author
> 
> firstly follow the account and mark star on the repo

done sir, please check

**Comment by MrDracs** [comment]
Please merge it if it's valid!

**Review by Gyanthakur — APPROVED** [review]

**Pull request merged**
